// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV5bqNaUUDmB3SBawLc7HXBI2WvAcOvV8',
    appId: '1:336138983965:web:edd47ae145c033f05a44f4',
    messagingSenderId: '336138983965',
    projectId: 'carlly-de5a1',
    authDomain: 'carlly-de5a1.firebaseapp.com',
    storageBucket: 'carlly-de5a1.appspot.com',
    measurementId: 'G-416GMZTRZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvKv1RcUQW7vrZpVkvMqizmv8cPXHM3qc',
    appId: '1:336138983965:android:e897b9c2737dc4d15a44f4',
    messagingSenderId: '336138983965',
    projectId: 'carlly-de5a1',
    storageBucket: 'carlly-de5a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuTZaCV2GYcdm8JZiH81q6tiEKfOLA5nA',
    appId: '1:336138983965:ios:ff7dcb7fe4f4558b5a44f4',
    messagingSenderId: '336138983965',
    projectId: 'carlly-de5a1',
    storageBucket: 'carlly-de5a1.appspot.com',
    iosBundleId: 'com.carllymotors.carllyuser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtor7UKczeG0ymGj1rpgug3xW7T82LcRw',
    appId: '1:270329644385:ios:615d1c416ccff54ddf3120',
    messagingSenderId: '270329644385',
    projectId: 'carsilla-6bfce',
    storageBucket: 'carsilla-6bfce.appspot.com',
    iosBundleId: 'com.carllymotors.carllyuser.RunnerTests',
  );
}